@startuml
hide circle
hide stereotype
hide members
hide methods
skinparam linetype ortho
skinparam class {
BackgroundColor<<LogicalModel>> #APPLICATION
BackgroundColor<<Profile>> #TECHNOLOGY
}
legend right
| <#APPLICATION>  Logical Model |
| <#TECHNOLOGY>  Profile |
endlegend
class "AdmissionEvaluation" <<LogicalModel>> [[StructureDefinition-LmAdmissionEvaluationCz.html]]

class "composition-cz-hdr" <<Profile>> [[StructureDefinition-cz-composition-hdr.html]]
"AdmissionEvaluation" <|. "composition-cz-hdr"
@enduml
