@startmindmap
* [[StructureDefinition-LogHospitalDischargeReportCz.html Propouštěcí zpráva z nemocnice]]
** [[StructureDefinition-LogHeaderHdrCz.html Hlavička dokumentu]]
** Tělo dokumentu
** Zobrazitelná forma dokumentu
** Přílohy
@endmindmap