@startmindmap
* [[StructureDefinition-HospitalDischargeReportCz.html Hospital Discharge Report]]
** [[StructureDefinition-Header.html header]]
** body
** Presented form
** Hospital Discharge Report attachments
@endmindmap