@startmindmap
* [[StructureDefinition-LMHospitalDischargeReportCz.html Propouštěcí zpráva z nemocnice]]
** [[StructureDefinition-LMHeaderHdrCz.html Hlavička dokumentu]]
** Tělo dokumentu
** Zobrazitelná forma dokumentu
** Přílohy
@endmindmap