@startuml
hide circle
hide stereotype
hide members
hide methods
skinparam linetype ortho
skinparam class {
BackgroundColor<<LogicalModel>> #APPLICATION
BackgroundColor<<Profile>> #TECHNOLOGY
}
legend right
| <#APPLICATION>  Logical Model |
| <#TECHNOLOGY>  Profile |
endlegend
class "PlanOfCare" <<LogicalModel>> [[StructureDefinition-PlanOfCareCz.html]]

class "carePlan-cz-hdr" <<Profile>> [[StructureDefinition-cz-carePlan-hdr.html]]
"PlanOfCare" <|. "carePlan-cz-hdr"
@enduml
