Logical: LogCzBirthSummaryHdrCz
Id: LogBirthSummaryCz
Title: "A.2.10 Porod"
Description: "Nemocniční propouštěcí zpráva - Sekce slouží k zaznamenání klíčových údajů o průběhu porodu a jeho výsledku."

* matka 0..* BackboneElement "A.2.10.1 Porod - matka"
* matka.gestacniStari 1..1 string "A.2.10.1.1 Gestační stáří" """Týden + den těhotenství, kdy žena rodila (např. 39+2)."""
* matka.gravidita 1..1 integer "A.2.10.1.2 Gravidita" """Počet těhotenství."""
* matka.parita 1..1 integer "A.2.10.1.3 Parita" """počet porodů."""
* matka.indukce 0..1 CodeableConcept "A.2.10.1.4 Preindukce / indukce porodu" """Charakterizuje nutnost a způsob vyvolání porodu. SNOMED CT."""
* matka.porodniPoraneni 1..* BackboneElement "A.2.10.1.5 Porodní poranění"
* matka.porodniPoraneni.text 0..* string "A.2.10.1.5.1 Porodní poranění textem"
* matka.porodniPoraneni.kod 0..* CodeableConcept "A.2.10.1.5.2 Porodní poranění kódovaně" """SNOMED CT."""
* matka.vicecetneTehotenstvi 0..1 boolean "A.2.10.1.6 Vícečetné těhotenství"
* matka.cetnost 0..1 integer "A.2.10.1.6.1 Četnost" """Četnost (pokud se jedná o vícečetné těhotenství)."""
* novorozenec 0..* BackboneElement "A.2.10.2 Plod/novorozenec"
* novorozenec.datumCasPorodu 1..1 dateTime "A.2.10.2.1 Datum a čas porodu"
* novorozenec.polohaPlodu 1..1 CodeableConcept "A.2.10.2.2 Poloha plodu v průběhu porodu" """SNOMED CT."""
* novorozenec.zpusobUkonceni 1..1 CodeableConcept "A.2.10.2.3 Způsob ukončení těhotenství" """SNOMED CT."""
* novorozenec.vitalita 1..1 CodeableConcept "A.2.10.2.4 Vitalita" """Narozen živý/mrtvý."""
* novorozenec.pohlavi 1..1 CodeableConcept "A.2.10.2.5 Pohlaví novorozence" """Výběr: chlapec / děvče / neurčeno."""
* novorozenec.hmotnost 1..1 Quantity "A.2.10.2.6 Porodní hmotnost novorozence" """v gramech."""
* novorozenec.delka 1..1 Quantity "A.2.10.2.7 Porodní délka novorozence" """v cm."""
* novorozenec.apgar 1..1 BackboneElement "A.2.10.2.8 Apgar skóre novorozence"
* novorozenec.apgar.min1 1..1 integer "A.2.10.2.8.1 Apgar skóre v 1. minutě"
* novorozenec.apgar.min5 1..1 integer "A.2.10.2.8.2 Apgar skóre v 5. minutě"
* novorozenec.apgar.min10 1..1 integer "A.2.10.2.8.3 Apgar skóre v 10. minutě"
* novorozenec.jmeno 0..1 string "A.2.10.2.9 Jméno novorozence"