Logical: LogCzHospitalStayCz
Id: LogHospitalStayCz
Title: "A.2.7 Průběh hospitalizace"
Description: "Nemocniční propouštěcí zpráva - Popis průběhu hospitalizace zahrnující diagnostické souhrny, výkony, léčbu, vyšetření i klinické shrnutí."

* diagnostickySouhrn 1..* Base "A.2.7.1 Diagnostický souhrn" """Všechny problémy/diagnózy, které ovlivňují péči během hospitalizace nebo které je důležité zaznamenat pro zajištění kontinuity péče. Rozlišuje se mezi problémy léčenými a neléčenými, dále mezi stavy přítomnými při přijetí, získanými během hospitalizace a neklasifikovatelnými. Popis je strukturovaný, dobře specifikovaný a kódovatelný."""
  * popisProblemu 1..1 string "A.2.7.1.1 - Popis problému" """Popis problému textem"""
  * detail 0..1 CodeableConcept "A.2.7.1.2 - Kód" """Formalizované vyjádření zdravotního problému kódem (klasifikace)."""
  * datumVzniku 1..1 dateTime "A.2.7.1.3 - Datum vzniku" """Datum vzniku onemocnění. Přesné nebo přibližné datum."""
  * datumVyreseniRemise 0..1 dateTime "A.2.7.1.4 - Datum vyřešení či remise" """Datum vyřešení či ustoupení problému do remise."""
  * kategorieProblemu 1..1 code "A.2.7.1.5 - Kategorie problému" """- POA - Stav byl přítomen při přijetí
- HAC - Stav byl získán v průběhu hospitalizace
- N/A - Nelze rozhodnout nebo není známo"""
  * kategoriePece 1..1 code "A.2.7.1.6 - Kategorie péče" """Klasifikace problému z hlediska poskytované péče.""" 
  * okolnostiVyreseni 0..1 string "A.2.7.1.7 - Okolnosti vyřešení" """Důvod změny stavu problému na neaktivní (např. chirurgický zákrok)."""
  * zavaznost 0..1 code "A.2.7.1.8 - Závažnost" """Subjektivní hodnocení závažnosti problému klinikem."""
  * stadiumOnemocneni 0..* CodeableConcept "A.2.7.1.9 - Stadium onemocnění" """Stadium/grading problému dle zvolené škály (např. TNM, MKN-O)."""
* vyznamneVykony 1..* Base "A.2.7.2 Významné výkony (procedury)" """Operace a ostatní „instrumentální“ intervence (endoskopické, intravaskulární) provedené v průběhu hospitalizace. Nezahrnuje čistě diagnostické výkony. Pokud nebyl proveden žádný výkon, uvede se IPS Absent/Unknown."""
  * kodVykonu 0..* CodeableConcept "A.2.7.2.1 - Kód výkonu" """Kód výkonu ve zvoleném kódovém systému"""
  * popisProcedury 1..1 string "A.2.7.2.2 - Popis procedury" """Popis výkonu volným textem."""
  * lokalizace 0..1 CodeableConcept "A.2.7.2.3 - Lokalizace" """Anatomická lokace a strana výkonu s použitím řízené terminologie."""
  * datumProvedeni 1..1 dateTime "A.2.7.2.4 - Datum provedení" """Datum provedení výkonu"""
  * duvodProvedeni 0..1 CodeableConcept "A.2.7.2.5 - Důvod provedení" """Důvod provedení výkonu textem nebo kódem"""
  * vysledek 0..1 CodeableConcept "A.2.7.2.6 - Výsledek" """Formalizované vyjádření výsledku výkonu. Aplikovatelné především na chirurgické výkony."""
  * komplikace 0..* CodeableConcept "A.2.7.2.7 - Komplikace" """Komplikace spojené s výkonem (v průběhu výkonu či bezprostředně po něm)."""
  * cilovyZdravProstredek 0..* Base "A.2.7.2.8 - Cílový zdravotnický prostředek" """Odkaz na zdravotnický prostředek, který byl implantován, odstraněn nebo s ním bylo jinak manipulováno (kalibrace, výměna baterie, nasazení protézy atd.) v průběhu procedury."""
* zp 1..* Base "A.2.7.3 Zdravotní pomůcky a implantáty" """Zavedené a používané zdravotní pomůcky nebo odebrané zdravotnické prostředky ovlivňující diagnostiku nebo léčbu. Pokud nejsou, uvede se důvod podle IPS."""
  * popisProstredku 1..1 CodeableConcept "A.2.7.3.1 - Popis zdravotnického prostředku" """Popis zdravotnického prostředku (implantovaného či externího) volným textem a/nebo kódem."""
  * identifikatorProstredku 0..1 Identifier "A.2.7.3.2 - Identifikátor prostředku" """Normalizovaný identifikátor, např. UDI, dle nařízení EU 2017/745"""
  * datumZavedeni 1..1 dateTime "A.2.7.3.3 - Datum zavedení" """Datum implantace či počátku užívání zdravotnického prostředku. Může být uvedeno i přibližné datum, pokud přesné datum není známo."""
  * datumOdstraneni 0..1 dateTime "A.2.7.3.4 - Datum odstranění" """Datum explantace či ukončení užívání zdravotnického prostředku. Může být uvedeno i přibližné datum, pokud přesné datum není známo."""
  * duvodPouziti 0..1 CodeableConcept "A.2.7.3.5 - Důvod použití" """Klinický důvod zavedení či odstranění zdravotnického prostředku vyjádřený textem a/nebo kódem zdravotního problému."""
* dalsiVyznamnaLecba 0..* Base "A.2.7.4 Další významná léčba" """Léčby, které nelze jednoznačně označit jako výkony, ale jsou významné (např. chemoterapie, dialýza, hemoperfuze, podpora oběhu, krevní deriváty apod.)."""
  * popisProcedury 1..1 string "A.2.7.4.1 - Popis procedury" """Popis výkonu volným textem."""
  * lokalizace 0..1 CodeableConcept "A.2.7.4.2 - Lokalizace" """Anatomická lokalizace a strana výkonu s použitím řízené terminologie."""
  * datumProvedeni 1..1 dateTime "A.2.7.4.3 - Datum provedení" """Datum provedení výkonu"""
  * duvodProvedeni 0..1 CodeableConcept "A.2.7.4.4 - Důvod provedení" """Důvod provedení výkonu textem nebo kódem"""
* medikace 0..* Base "A.2.7.5 Medikace" """Medikamentózní léčba během hospitalizace, jejíž znalost je významná pro další péči. Patří sem léčiva podaná a ukončená během hospitalizace nebo pokračující krátkodobě. Léčiva doporučená i po propuštění budou uvedena v části Doporučení."""
  * indikace 0..1 CodeableConcept "A.2.7.5.1 - Indikace" """Důvod medikace. Důvod může být popsán textem případně odkazem na zdravotní důvod (zdravotní problém v seznamu problémů)."""
  * kodSUKL 1..1 string "A.2.7.5.2 - Kód SUKL" """Kód léčiva dle databáze SÚKL"""
  * nazevLecivehoPripravku 1..1 string "A.2.7.5.3 - Název léčivého přípravku" """Registrovaný název léčiva dle databáze léčivých přípravků."""
  * aktivniLatky 0..* CodeableConcept "A.2.7.5.4 - Aktivní látky" """Seznam aktivních látek v léčivu odvozený od záznamu HVLP nebo IVLP přípravku v databázi SUKL (DLP). Aktivní látky jsou uváděny názvem a případně také kódem ATC či IDMP dle registru substancí SRS."""
  * sila 0..* Quantity "A.2.7.5.5 - Síla" """Síla aktivní léčivé látky obsažené v léčivém přípravku. Síla se vyjadřuje ve vztahu k jednotce podání. Např. 500mg v tabletě."""
  * formaLeciva 0..1 CodeableConcept "A.2.7.5.6 - Forma léčiva" """Léková forma obsažená v balení vyjádřená kódem. Např. Sirup, tableta apod."""
  * davkovani 0..* string "A.2.7.5.7 - Dávkování" """Frekvence a počet jednotek podání volným textem nebo formalizovaně."""
  * cestaPodani 0..1 CodeableConcept "A.2.7.5.8 - Cesta podání" """Cesta podání"""
  * obdobiPodavani 0..1 Period "A.2.7.5.9 - Období podávání" """Časový interval kdy pacientovi byla, případně nebyla medikace podávána."""
* vysledkyVysetreni 0..* string "A.2.7.6 Výsledky vyšetření" """Významné výsledky funkčních, diagnostických a zobrazovacích vyšetření, provedených během hospitalizace. Výsledky s nezpracovaným stavem („registered“) mají být uvedeny odděleně."""
* klinickeShrnuti 1..1 Base "A.2.7.7 Klinické shrnutí" """Podrobný popis důvodu a průběhu hospitalizace jako celku. Může být zakončeno klinickou úvahou (dif. dg., vysvětlení souvislostí) v klinicky složitých případech."""
  * souhrnProblemu 1..* Base "A.2.7.7.1 Klinický souhrn problému" """Souhrnný popis důvodu a průběhu hospitalizace za konkrétní problém."""
    * popisProblemu 1..1 string "A.2.7.7.1.1 Popis problému" """Popis problému textem."""
    * duvod 1..1 string "A.2.7.7.1.2 Důvod a průběh hospitalizace" """Podrobný popis důvodu a průběhu hospitalizace za celý pobyt."""
  * klinickaUvaha 0..1 string "A.2.7.7.2 Klinická úvaha" """Zakončení klinického shrnutí klinickou úvahou (diferenciální diagnostika, vysvětlení složitých stavů apod.)."""
